-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  role USER-DEFINED NOT NULL DEFAULT 'broker'::user_role,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  broker_id uuid,
  phone_country_code text DEFAULT '91'::text,
  phone_country_iso text DEFAULT 'IN'::text,
  search_text text,
  fts tsvector,
  gender USER-DEFINED DEFAULT 'other'::user_gender,
  date_of_birth date,
  notes text,
  cover_image jsonb,
  inactive_reason text,
  delete_reason text,
  activated_at timestamp with time zone,
  inactivated_at timestamp with time zone,
  is_email_verified boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.brokers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  plan text,
  onboarding_status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  address_id uuid,
  search_text text,
  fts tsvector,
  auto_approve_video_requests boolean NOT NULL DEFAULT false,
  setup_details jsonb DEFAULT '{"account_created": true, "facebook_connected": false, "business_info_added": false, "instagram_connected": false, "properties_imported": false}'::jsonb,
  CONSTRAINT brokers_pkey PRIMARY KEY (id),
  CONSTRAINT brokers_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id)
);
CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_address text NOT NULL,
  latitude double precision,
  longitude double precision,
  city text,
  pincode text,
  state text,
  country text,
  landmark text,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  search_text text,
  fts tsvector,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT addresses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  facebook_user_id text,
  page_id text,
  page_name text,
  page_access_token text,
  instagram_account_id text,
  instagram_username text,
  access_token text NOT NULL,
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_connected boolean DEFAULT true,
  search_text text,
  fts tsvector,
  ad_account_id text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_accounts_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.social_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  page_id text NOT NULL,
  post_id text NOT NULL,
  caption text,
  media_urls jsonb DEFAULT '[]'::jsonb,
  permalink text,
  views_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  likes_count integer DEFAULT 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_text text,
  fts tsvector,
  property_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT social_posts_pkey PRIMARY KEY (id),
  CONSTRAINT social_posts_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT social_posts_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.social_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_name text NOT NULL,
  notes text,
  social_post_id uuid,
  search_text text,
  fts tsvector,
  phone text,
  phone_country_code text DEFAULT '91'::text,
  phone_country_iso text DEFAULT 'IN'::text,
  property_details text,
  broker_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT social_leads_pkey PRIMARY KEY (id),
  CONSTRAINT social_leads_social_post_id_fkey FOREIGN KEY (social_post_id) REFERENCES public.social_posts(id),
  CONSTRAINT social_leads_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  address_id uuid,
  property_title text NOT NULL,
  property_description text,
  property_type USER-DEFINED NOT NULL DEFAULT 'apartment'::property_type_enum,
  listing_type USER-DEFINED NOT NULL DEFAULT 'sale'::listing_type_enum,
  price numeric NOT NULL,
  area numeric NOT NULL,
  area_unit USER-DEFINED DEFAULT 'sqft'::area_unit_enum,
  bedrooms integer DEFAULT 0,
  bathrooms integer DEFAULT 0,
  balconies integer DEFAULT 0,
  parking integer DEFAULT 0,
  floor_number integer,
  total_floors integer,
  furnishing_status USER-DEFINED DEFAULT 'unfurnished'::furnishing_status_enum,
  property_status USER-DEFINED DEFAULT 'available'::property_status_enum,
  construction_status USER-DEFINED DEFAULT 'ready_to_move'::construction_status_enum,
  facing USER-DEFINED DEFAULT 'east'::facing_direction_enum,
  amenities jsonb DEFAULT '[]'::jsonb,
  medias jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_text text,
  fts tsvector,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT properties_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.video_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  broker_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::video_request_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  notes text,
  admin_approval_status USER-DEFINED NOT NULL DEFAULT 'pending'::video_request_approval_status,
  completed_at timestamp with time zone,
  cancel_reason text,
  admin_cancel_reason text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  cancelled_by_user_id uuid,
  CONSTRAINT video_requests_pkey PRIMARY KEY (id),
  CONSTRAINT video_requests_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT video_requests_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT video_requests_cancelled_by_user_id_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.attachments (
  id bigint NOT NULL DEFAULT nextval('attachments_id_seq'::regclass),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  url text NOT NULL,
  r2_key text,
  file_name text,
  file_type text,
  file_size bigint,
  is_cover boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT attachments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_request_id uuid NOT NULL UNIQUE,
  broker_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT chat_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT chat_rooms_video_request_id_fkey FOREIGN KEY (video_request_id) REFERENCES public.video_requests(id),
  CONSTRAINT chat_rooms_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_type character varying NOT NULL DEFAULT 'broker'::character varying,
  message text,
  message_type USER-DEFINED NOT NULL DEFAULT 'text'::chat_message_type,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  medias jsonb DEFAULT '[]'::jsonb,
  is_edited boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  location_data jsonb DEFAULT '{}'::jsonb,
  reply_message_id uuid,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_reply_message_id_fkey FOREIGN KEY (reply_message_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid,
  notification_type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  receiver_ids ARRAY,
  video_request_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT notifications_video_request_id_fkey FOREIGN KEY (video_request_id) REFERENCES public.video_requests(id)
);
CREATE TABLE public.user_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text,
  otp text NOT NULL,
  otp_type USER-DEFINED NOT NULL,
  expiry_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_otps_pkey PRIMARY KEY (id),
  CONSTRAINT user_otps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ad_campaign_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL UNIQUE,
  gender USER-DEFINED NOT NULL DEFAULT 'all'::campaign_gender CHECK (gender = ANY (ARRAY['all'::text, 'male'::text, 'female'::text])),
  area_details jsonb DEFAULT '[]'::jsonb,
  targeting_suggestions jsonb DEFAULT '[]'::jsonb,
  start_age_range integer NOT NULL DEFAULT 18 CHECK (start_age_range >= 13 AND start_age_range <= 100),
  end_age_range integer NOT NULL DEFAULT 65,
  campaign_start_time text,
  campaign_end_time text,
  campaign_is_all_day boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ad_campaign_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ad_campaign_settings_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);