// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ph_KMEyq3jORvbNPESIxr7LEfFzNPS8',
    appId: '1:872541492683:web:a6bbcdf395a6ca3a00924e',
    messagingSenderId: '872541492683',
    projectId: 'the-realty-bazaar',
    authDomain: 'the-realty-bazaar.firebaseapp.com',
    storageBucket: 'the-realty-bazaar.firebasestorage.app',
    measurementId: 'G-SHLT4GW6XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6a0PBkdOvKw7UCqKB9NYr-2gkh2AIuGs',
    appId: '1:872541492683:android:d4e062e8b189687d00924e',
    messagingSenderId: '872541492683',
    projectId: 'the-realty-bazaar',
    storageBucket: 'the-realty-bazaar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLN9bwVWcW4k0m1FjfKil-AlsaX4Xq_w',
    appId: '1:872541492683:ios:6b6f2b1bb100adbb00924e',
    messagingSenderId: '872541492683',
    projectId: 'the-realty-bazaar',
    storageBucket: 'the-realty-bazaar.firebasestorage.app',
    iosBundleId: 'com.therealtybazaar.broker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnLN9bwVWcW4k0m1FjfKil-AlsaX4Xq_w',
    appId: '1:872541492683:ios:6b6f2b1bb100adbb00924e',
    messagingSenderId: '872541492683',
    projectId: 'the-realty-bazaar',
    storageBucket: 'the-realty-bazaar.firebasestorage.app',
    iosBundleId: 'com.therealtybazaar.broker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Ph_KMEyq3jORvbNPESIxr7LEfFzNPS8',
    appId: '1:872541492683:web:906f24d98c278c3900924e',
    messagingSenderId: '872541492683',
    projectId: 'the-realty-bazaar',
    authDomain: 'the-realty-bazaar.firebaseapp.com',
    storageBucket: 'the-realty-bazaar.firebasestorage.app',
    measurementId: 'G-KVQ8D1DHT0',
  );
}
